# See https://docs.rubocop.org/rubocop/configuration
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
