# See https://docs.rubocop.org/rubocop/configuration
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
AllCops:
  Exclude:
    - "config/initializers/devise.rb"
    - "bin/bundle"
